### ISSUE TITLE
molbit sequences

### ISSUE THREAD

**Issue by enovoa** [uwmisl/Porcupine#2]
Hello! Thanks for sharing your work in bioRxiv. I was wondering if you could make available the fasta sequences for all 96 molbit sequences after 31 iterations of the evolutionary model? I could find the fasta with the corresponding squiggles in Supp Figure 5, but a plain txt/csv file with the individual fasta sequences would be very useful. Where can I find this? Thanks so much, and congrats on the preprint! Eva

**Comment by kdoroschak** [comment]
Hi Eva,

Thanks for reaching out! You can find the sequences here: https://github.com/uwmisl/Porcupine/blob/master/porcupine_sequences.fa Is this what you had in mind? We intend to include this as a supplementary file with the final publication as well, so it's easier to find.

Just want to note -- If you end up using any of these sequences for your RNA barcoding, I would recommend selecting those with read counts that hovered around the median (e.g. 11, 29, 37, 44, 67 as in Supp. Fig 8 in the preprint), due to the still-unexplained variation in read counts. That way no correction should be needed. I'd also be curious to see how it goes, so please let me know if you do try them out!

Best,
Katie

**Comment by enovoa** [comment]
Hi Katie, 
Thank you very much! Yes, that's exactly what I was looking for :)
