### ISSUE TITLE
Documentation for installing and running the molbit_design notebooks is incomplete

### ISSUE THREAD

**Issue by patbohn** [uwmisl/Porcupine#4]
Hi, very interesting work! 

I would like to design some shorter sequences (~20mers) with a high distance in dtw space, so am trying to run the molbit_design jupyter notebook. I've came across some issues regarding this:

1) Is it possible to link to the nupyck package on your documentation? Googling it might result in installing a wrong package/version. 
_(also unrelated to your work but maybe helpful for others, the nupyck install instructions / module structure was broken for me because it used relative referencing in a submodule; fixed by moving the helper scripts in "apps" to the "nupyck" folder and editing the "__init__.py" to reflect that)_

2) "natsort" and "imageio" packages also need to be installed

3) I cannot find the pore_utils package that contains the smith_waterman algorithm. 

Could you help me with the 3rd point? 

Best wishes, 
Patrick

**Comment by kdoroschak** [comment]
Hi! I apologize for just seeing this now.

1. Unfortunately, no it is not possible, as the license of NUPACK is restrictive and the python bindings used here cannot be released. However, since I wrote this, someone released a mfe package that works reasonably well, and I've been using that for other projects since it came out. The package is [seqfold](https://pypi.org/project/seqfold/). It returns similar results to NUPACK, although not exact. Good enough for this application.
2. Thanks, I'll add that to the documentation.
3. Sorry, this was overlooked when preparing the submission. You can now find it at `pore-utils` where it can be pip installed. I'm sure there's a better way to import within the context of this project, however, that's the quickest way to make this available.
